/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ImprimilfiladeJtable;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import AdmdeVentas.*;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterException;
/**
 *
 * @author Jesus Arias
 */
public class TablaD extends javax.swing.JFrame {
//IngresoDatosCli ingresocli=null;
DefaultTableModel tabladatos;
    String fila[][]={};
    String columna[]={"#","Nombre","Apellido","Fecha de nacimiento","Numero de Documento","Sexo","Estado Civil","Hijos","Estudios","Direccion","Codigo Postal","Provinvia","Pais"};
    //TablaD tabladat=null;
    /**
     * Creates new form Tabla
     */
    public TablaD() {
        initComponents();
        tabladatos=new DefaultTableModel(fila,columna );
         tblDatos.setModel(tabladatos);
          
    }

    FilaSelected_tabla z=new FilaSelected_tabla();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Nombres", "Apellidos", "Fecha de nacimiento", "Numero de Documento", "Sexo", "Estado Civil", "Hijos", "Estudios", "Direccion", "Codigo Postal", "Provinvia", "Pais"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);
        if (tblDatos.getColumnModel().getColumnCount() > 0) {
            tblDatos.getColumnModel().getColumn(11).setResizable(false);
        }

        jButton1.setText("Manda a imprimir a una tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Manda a imprimir a un texto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exporta la Fila");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton1)
                .addGap(101, 101, 101)
                .addComponent(jButton2)
                .addGap(88, 88, 88)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public int numero=1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int select= tblDatos.getSelectedRow();
       
        try {
            if (select==-1) {
                JOptionPane.showMessageDialog(null, "PORFAVOR SELECIONE UNA FILA", "ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
//"Nombre","Apellido","Fecha de nacimiento","Numero de Documento","Sexo","Estado Civil","Hijos","Estudios","Direccion","Codigo Postal","Provinvia","Pais"                
            }else{
            String nombre="",apellido="",direccion="",fechanac="";
              String dni="",sexo="",estado="",hijos="",estudios="";
               String direc="",cp,provincia="",pais="";
            //int subtotal,saco,sugerido,pesoneto,pesobruto;
                nombre=tblDatos.getValueAt(select, 1).toString();
                apellido=tblDatos.getValueAt(select, 2).toString();
                fechanac=tblDatos.getValueAt(select, 3).toString();
                dni=tblDatos.getValueAt(select, 4).toString();
                sexo=tblDatos.getValueAt(select, 5).toString();        
                estado=tblDatos.getValueAt(select, 6).toString();        
                hijos=tblDatos.getValueAt(select, 7).toString();        
                estudios=tblDatos.getValueAt(select, 8).toString();        
                direc=tblDatos.getValueAt(select, 9).toString();  
                cp=tblDatos.getValueAt(select, 10).toString(); 
                provincia=tblDatos.getValueAt(select, 11).toString();        
                pais=tblDatos.getValueAt(select, 12).toString();        
                
            Object file[]={numero,nombre,apellido,fechanac,dni,sexo,estado,hijos,estudios,direc,cp,provincia,pais};
                z.tablaimp.addRow(file);
                numero++;
                //En vialos datos al form 3 en el form3 titnten que esta los jTextField como public static
              // form3.jTextField7.setText(String.valueOf(totalpesoBruto()));
             //  form3.jTextField8.setText(String.valueOf(totalPesoNeto()));
             //  form3.jTextField9.setText(String.valueOf(totalpagar()));
              // TablaD.setValueAt("ATENDIDO", select, 6);
               z.setVisible(true);
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"NO SE COMPLETO LA ACCION","ERROR",JOptionPane.ERROR_MESSAGE);
            
        }
        /*
        //comando imprimir
        try {
            tblDatos.print(); // Imprime el jTable
        } catch (PrinterException ex) { }
           */           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
