/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controlador_listas_de_recibos;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jesus Arias
 */
public class form2 extends javax.swing.JFrame {

    /**
     * Creates new form form2
     */
    
    DefaultTableModel tablaRecivos;
    String fila[][]={};
    String columna[]={"#RECIBO","PRODUCTOR","PESO NETO","PESO BRUTO","PRESIO SUGERIDO","# DE SACO","ESTADO"};
    
    
    
    public form2() {
        initComponents();
       
         tablaRecivos=new DefaultTableModel(fila,columna );
         jTable2.setModel(tablaRecivos);
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("RECIVOS INGRESADOS");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#RECIBO", "PRODUCTOR", "PESO NETO", "PESO BRUTO", "PRESIO SUGERIDO", "# DE SACO", "ESTADO "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jButton1.setText("MOSTRAR REMISION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CARGAR REMISION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
form3 z=new form3();
    
  public int totalsaco(){
        int suma=0;
        for (int i = 0; i < z.tablaRemicion.getRowCount(); i++) {
            suma=suma+Integer.parseInt(z.tablaRemicion.getValueAt(i, 1).toString());
        }
        return suma;
    }
    
    
    public int totalpesoBruto(){
        int suma=0;
        for (int i = 0; i < z.tablaRemicion.getRowCount(); i++) {
            suma=suma+Integer.parseInt(z.tablaRemicion.getValueAt(i, 3).toString());
        }
        return suma;
    }
    
    public int totalPesoNeto(){
        int suma=0;
        for (int i = 0; i < z.tablaRemicion.getRowCount(); i++) {
            suma=suma+Integer.parseInt(z.tablaRemicion.getValueAt(i, 4).toString());
        }
        return suma;
    }
    
    
    public int totalpagar(){
        int suma=0;
        for (int i = 0; i < z.tablaRemicion.getRowCount(); i++) {
            suma=suma+Integer.parseInt(z.tablaRemicion.getValueAt(i, 6).toString());
        }
        return suma;
    }

    

    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        z.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public int reci=1;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //se manda losdatos de la fila seleccionanda a un Jtable
        int select= jTable2.getSelectedRow();
       
        try {
            if (select==-1) {
                JOptionPane.showMessageDialog(null, "PORFAVOR SELECIONE UNA FILA", "ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
                
            }else{
            String produ="";
            int subtotal,saco,sugerido,pesoneto,pesobruto;
                 produ=jTable2.getValueAt(select, 1).toString();
                pesoneto=Integer.parseInt(jTable2.getValueAt(select, 2).toString());
                pesobruto=Integer.parseInt(jTable2.getValueAt(select, 3).toString());
                sugerido=Integer.parseInt(jTable2.getValueAt(select, 4).toString());
                saco=Integer.parseInt(jTable2.getValueAt(select, 5).toString());
                subtotal=saco*sugerido;
                
            Object file[]={reci,produ,saco,pesobruto,pesoneto,sugerido,subtotal};
                z.tablaRemicion.addRow(file);
                reci++;
                //En vialos datos al form 3 en el form3 titnten que esta los jTextField como public static
               form3.jTextField7.setText(String.valueOf(totalpesoBruto()));
               form3.jTextField8.setText(String.valueOf(totalPesoNeto()));
               form3.jTextField9.setText(String.valueOf(totalpagar()));
               tablaRecivos.setValueAt("ATENDIDO", select, 6);
              
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"NO SE COMPLETO LA ACCION","ERROR",JOptionPane.ERROR_MESSAGE);
            
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
