package Codoacodo;
/*
2) Confeccionar un menú de opciones. Al desplegarlo, deberá contener 3 (tres) opciones de colores (rojo,
verde y azul) que permitan cambiar el color de fondo del JFrame. Si necesitas ayuda para resolver el
ejercicio, podés ver el siguiente video: https://youtu.be/Rn1v_SN3Wac (Cómo insertar menús y
submenús en Java)
*/
import java.awt.Color;
import javax.swing.JFrame;

/**
 * @author Jesus Arias
 */
public class codoacodo_EjOb_unidad4parte4ej2 extends javax.swing.JFrame {

    /**
     * Creates new form ventanaColor
     */
    public codoacodo_EjOb_unidad4parte4ej2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        BarraMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        //codigo
        opRojo = new javax.swing.JMenuItem();
        //codigo
        opVerde = new javax.swing.JMenuItem();
        //codigo
        opAzul = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        opRojo.setText("Rojo");
        opRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opRojoActionPerformed(evt);
            }
        });
        jMenu1.add(opRojo);

        opVerde.setText("Verde");
        opVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opVerdeActionPerformed(evt);
            }
        });
        jMenu1.add(opVerde);

        opAzul.setText("Azul");
        opAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opAzulActionPerformed(evt);
            }
        });
        jMenu1.add(opAzul);

        BarraMenu.add(jMenu1);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    
    
    
    private void opVerdeActionPerformed(java.awt.event.ActionEvent evt) {                                        
       this.getContentPane().setBackground(Color.GREEN);
    }                                       

    private void opRojoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        this.getContentPane().setBackground(Color.RED);
    }                                      

    private void opAzulActionPerformed(java.awt.event.ActionEvent evt) {                                       
     this.getContentPane().setBackground(Color.BLUE);
    }                                      
         
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaColor().setVisible(true);
            }
        });
        
        
       
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem opAzul;
    private javax.swing.JMenuItem opRojo;
    private javax.swing.JMenuItem opVerde;
    // End of variables declaration                   
}
